name: "JFrog-GitHub NPM Publish OIDC Integration"
on: push

permissions:
  contents: read
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Get id token
          run: |
            ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=jfrog-github-sunil" | jq .value | tr -d '"')
            echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV
            echo ID Token is ${{ env.ID_TOKEN }}
        - name: Exchange token with access
          env:
            ID_TOKEN: ${{ env.ID_TOKEN }}
            POC_URL: https://psazuse.jfrog.io/
          run: |
            ACCESS_TOKEN=$(curl -XPOST "${POC_URL}/token" -d "{\"token\": \"${ID_TOKEN}\"}" | jq .access_token | tr -d '"')
            echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build
          run: |
            make build
        - name: Deploy to artifactory
          env:
            ID_TOKEN: ${{ env.ACCESS_TOKEN }}
            POC_URL: ${{ vars.POC_URL }}
          run: |
            curl -H "Authorization: Bearer $ACCESS_TOKEN" -T oidc-poc "${POC_URL}/artifactory/access-oidc-poc/oidc-poc-$(date +%Y%m%d%H%M%S)"
